[project]
name = "ibet-network-tests"
version = "2.8"
description = "E2E tests from python client to ibet-Core node containers"
authors = [{ name = "BOOSTRY Co., Ltd.", email = "dev@boostry.co.jp" }]
requires-python = "==3.14.*"
dependencies = []

[dependency-groups]
dev = [
    "eth-keyfile>=0.8.1,<0.9",
    "eth-utils>=6.0.0,<6.1",
    "py-solc-x==2.0.5",
    "pycryptodome>=3.23.0,<4",
    "pytest>=9.0.3,<10",
    "web3==7.16.0",
]

[tool.uv]
exclude-newer = "7 days"
