version: '3'
services:
  validator-0:
    hostname: validator-0
    image: ghcr.io/boostryjp/ibet-localnet/validator:v2.3.0_beta1
    volumes:
      - /home/ubuntu/quorum_data/v0:/eth
    environment:
      - PRIVATE_CONFIG=ignore
      - rpccorsdomain=*
      - rpcvhosts=*
      - maxpeers=*
      - nodekeyhex='2ad84f0c2e0b87137bd91a2aee2b28cc0bc7eba38922d752bb080d5b4fa34506'
      - identity='validator-0'
      - testQBFTBlock=4
      - berlinBlock=4
      - cache=1024
    ports:
      - '30303:30303'
      - '8545:8545'
    networks:
      app_net:
        ipv4_address: 172.16.239.10
    restart: always
  validator-1:
    hostname: validator-1
    image: ghcr.io/boostryjp/ibet-localnet/validator:v2.3.0_beta1
    volumes:
      - /home/ubuntu/quorum_data/v1:/eth
    environment:
      - PRIVATE_CONFIG=ignore
      - rpccorsdomain=*
      - rpcvhosts=*
      - maxpeers=*
      - nodekeyhex='844d84c4af13a753eea5528941d7b17d14796717a7a491830bda49af2662c725'
      - identity='validator-1'
      - testQBFTBlock=4
      - berlinBlock=4
      - cache=1024
    ports:
      - '30304:30303'
      - '8546:8545'
    networks:
      app_net:
        ipv4_address: 172.16.239.11
    restart: always
  validator-2:
    hostname: validator-2
    image: ghcr.io/boostryjp/ibet-localnet/validator:v2.3.0_beta1
    volumes:
      - /home/ubuntu/quorum_data/v2:/eth
    environment:
      - PRIVATE_CONFIG=ignore
      - rpccorsdomain=*
      - rpcvhosts=*
      - maxpeers=*
      - nodekeyhex='9fa7eb5f2588d4fd510aabfacbf99f2e0a9bca56c75b8ea66c511b7850d5d1be'
      - identity='validator-2'
      - testQBFTBlock=4
      - berlinBlock=4
      - cache=1024
    ports:
      - '30305:30303'
      - '8547:8545'
    networks:
      app_net:
        ipv4_address: 172.16.239.12
    restart: always
  validator-3:
    hostname: validator-3
    image: ghcr.io/boostryjp/ibet-localnet/validator:v2.3.0_beta1
    volumes:
      - /home/ubuntu/quorum_data/v3:/eth
    environment:
      - PRIVATE_CONFIG=ignore
      - rpccorsdomain=*
      - rpcvhosts=*
      - maxpeers=*
      - nodekeyhex='13fe4f966e610ff5ac67965d02fd63a5883c6932a4faa1d2ca974f9e9595adc4'
      - identity='validator-3'
      - testQBFTBlock=4
      - berlinBlock=4
      - cache=1024
    ports:
      - '30306:30303'
      - '8548:8545'
    networks:
      app_net:
        ipv4_address: 172.16.239.13
    restart: always
  general-0:
    hostname: general-0
    image: ghcr.io/boostryjp/ibet-localnet/general:v2.3.0_beta1
    volumes:
      - /home/ubuntu/quorum_data/g0:/eth
    environment:
      - PRIVATE_CONFIG=ignore
      - rpccorsdomain=*
      - rpcvhosts=*
      - maxpeers=*
      - identity='general-0'
      - testQBFTBlock=4
      - berlinBlock=4
      - syncmode=snap
      - cache=2048
    ports:
      - '30307:30303'
      - '8549:8545'
    networks:
      app_net:
        ipv4_address: 172.16.239.14
    restart: always
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
