name: Build and Push

on:
  push:
    tags:
      - v*

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      # ibet (Validator)
      - name: Build and Push (ibet / Validator)
        uses: docker/build-push-action@v2
        with:
          context: ./ibet-network/validator
          file: ./ibet-network/validator/Dockerfile
          push: true
          tags: ghcr.io/boostryjp/ibet-network/validator:${{ steps.get_tag_name.outputs.VERSION }}
