name: Build (ibet for fin General)

on:
  push:
    tags:
      - v*

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Get tag name
        id: get_tag_name
        run: echo VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT

      # ibet for Fin (General)
      - name: Build and Push (ibet for Fin / General)
        uses: docker/build-push-action@v5
        with:
          context: ./ibet-for-fin-network/general
          file: ./ibet-for-fin-network/general/Dockerfile
          no-cache: true
          push: true
          tags: ghcr.io/boostryjp/ibet-fin-network/general:${{ steps.get_tag_name.outputs.VERSION }}
